[package]
name = "KangVip"
version = "8.0.0-vOW"
edition = "2021"

[dependencies]
mimalloc = { version = "0.1.39", default-features = false }
ark-ec = "0.4.0"
ark-ff = { version = "0.4.0", features = ["asm"] }
ark-secp256k1 = "0.4.0"
bs58 = "0.5.0"
clap = { version = "4.4.11", features = ["derive"] }
hex = "0.4.3"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
ripemd = "0.1.3"
sha2 = "0.10.8"
ctrlc = "3.4"
hashbrown = "0.14.3"
ahash = "0.8.11"
crossbeam-channel = "0.5.12"
crc32fast = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# KHAI BÁO DÀNH RIÊNG CHO FILE build.rs NẰM Ở ĐÂY:
[build-dependencies]
cc = "1.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
